### ISSUE TITLE
images referenced in .md

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-central-deploy-action#3]
currently it looks like that referenced images in an `.md` need to be put into the `htdocs` folder. the `htdocs` folder was intented to serve static resources that are not related to the content but are related to code.

also given that in existing repos with arbitrary `.md` the expectation is set that (images) references are relative to the `.md`.

**Comment by kptdobe** [comment]
I tested and moved the `img` folder at the root of the project (i.e. outside of `htdocs`) and it works, images are rendered.

**Comment by koraa** [comment]
Closed in favor of #5
